In [2]:
from numpy import random
print(random.randint(1,100))#random integer in the given range
print(random.rand())#float number 0-1

90
0.8296617322212559


In [3]:
#creating n dimensional array with random values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[20 55 83]
[[75  6 48 83]
 [91  4 43 59]
 [94 35 89 16]]
[[[48 30]
  [ 1  0]
  [36 37]
  [44 16]]

 [[48 80]
  [ 2 59]
  [50 40]
  [76 73]]

 [[60 20]
  [96 24]
  [32 78]
  [86 58]]]


In [4]:
#creating n dimensional array with random floating point values
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.13864230747313577
[0.52569387 0.49785838 0.14666592]
[[0.16808018 0.3670327  0.83283459]
 [0.64938774 0.58278927 0.43325746]]


In [6]:
a= random.randint(100,size=(3,2)).ravel()
a

array([42, 45, 92, 18, 19, 60])

In [7]:
#single element will be selected
random.choice(a)

18

In [9]:
#for generating an array with the given shape and elements from the given list
random.choice([1,2,3,4,5],size=(4,4))

array([[2, 1, 1, 3],
       [3, 2, 3, 5],
       [5, 5, 5, 3],
       [5, 3, 4, 4]])

### pandas:
1. Data manipulation,analysis and cleaning
2. Tabular,Unlabeled

### Creating a DataFrame
1. using 2 directories

In [5]:
import pandas as pd
import numpy as np
dict1={'a':1,'b':2,'c':3,'d':4,'e':5}
dict2={'a':5,'b':6,'c':7,'d':8,'e':9}
data={"First":dict1,"Second":dict2}
df=pd.DataFrame(data,dtype=np.int32)
df

First  Second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [7]:
# simple dicionary-->dataframe
d1 = {"name":["aashrith","aash","pichi"],"address":["hyd","wgl","goa"]}
df1 = pd.DataFrame(d1)
df1

name address
0  aashrith     hyd
1      aash     wgl
2     pichi     goa

In [14]:
# using series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([11.1,12.2,13.3,14.4,15.5,16.6,17.7,18.8,19.0,20.0])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"coloumn1":s1,"coloumn2":s2,"coloumn3":s3}
df3 = pd.DataFrame(data)
df3

coloumn1  coloumn2 coloumn3
0         1      11.1        a
1         2      12.2        b
2         3      13.3        c
3         4      14.4        d
4         5      15.5        e
5         6      16.6        f
6         7      17.7        g
7         8      18.8        h
8         9      19.0        i
9        10      20.0        j

## selecting the data from the data frame
1. loc
2. iloc

In [18]:
type(df3)

pandas.core.frame.DataFrame

In [15]:
df3["coloumn2"]

0    11.1
1    12.2
2    13.3
3    14.4
4    15.5
5    16.6
6    17.7
7    18.8
8    19.0
9    20.0
Name: coloumn2, dtype: float64

In [16]:
df3[["coloumn2","coloumn3"]]

coloumn2 coloumn3
0      11.1        a
1      12.2        b
2      13.3        c
3      14.4        d
4      15.5        e
5      16.6        f
6      17.7        g
7      18.8        h
8      19.0        i
9      20.0        j

In [17]:
#single coloumn
df3.loc[:,"coloumn1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: coloumn1, dtype: int64

In [20]:
#extracting multiple coloumn values
df3.loc[0:5,["coloumn1","coloumn2"]]

coloumn1  coloumn2
0         1      11.1
1         2      12.2
2         3      13.3
3         4      14.4
4         5      15.5
5         6      16.6

In [23]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: coloumn1, dtype: int64

In [24]:
df3.iloc[0:4,0:1]

coloumn1
0         1
1         2
2         3
3         4

## Retrieving the information of DataFrame

In [25]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
coloumn1    10 non-null int64
coloumn2    10 non-null float64
coloumn3    10 non-null object
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [26]:
df3.shape

(10, 3)

In [28]:
df3.columns

Index(['coloumn1', 'coloumn2', 'coloumn3'], dtype='object')

In [29]:
df3.index

RangeIndex(start=0, stop=10, step=1)

## Viewing data from DataFrame
1. head()
2. tail()
3. sample()

In [31]:
#First 5 rows
df3.head()


coloumn1  coloumn2 coloumn3
0         1      11.1        a
1         2      12.2        b
2         3      13.3        c
3         4      14.4        d
4         5      15.5        e

In [32]:
df3.head(3)

coloumn1  coloumn2 coloumn3
0         1      11.1        a
1         2      12.2        b
2         3      13.3        c

In [35]:
df3.tail()

coloumn1  coloumn2 coloumn3
5         6      16.6        f
6         7      17.7        g
7         8      18.8        h
8         9      19.0        i
9        10      20.0        j

In [36]:
df3.tail(2)

coloumn1  coloumn2 coloumn3
8         9      19.0        i
9        10      20.0        j

In [37]:
df3.sample()

coloumn1  coloumn2 coloumn3
3         4      14.4        d

In [38]:
df3.sample(2)

coloumn1  coloumn2 coloumn3
2         3      13.3        c
8         9      19.0        i

In [39]:
df3.describe()

coloumn1   coloumn2
count  10.00000  10.000000
mean    5.50000  15.860000
std     3.02765   3.063114
min     1.00000  11.100000
25%     3.25000  13.575000
50%     5.50000  16.050000
75%     7.75000  18.525000
max    10.00000  20.000000

In [49]:
#renaming the column headers
df3=df3.rename(columns={"column1":"First",
                         "column2":"Second",
                         "column3":"Third"})
df3

coloumn1  coloumn2 coloumn3
0         1      11.1        a
1         2      12.2        b
2         3      13.3        c
3         4      14.4        d
4         5      15.5        e
5         6      16.6        f
6         7      17.7        g
7         8      18.8        h
8         9      19.0        i
9        10      20.0        j